### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by WangWenhao0716** [KaiyuYue/torchshard#2]
Hi, thanks for the excellent job!
When I install it from pip, and
```
import torchshard as ts
ts.init_process_group(group_size=2) 
```
The AttributeError occurs:
```
AttributeError: module 'torchshard' has no attribute 'init_process_group'
```

**Comment by kaiyuyue** [comment]
Ops! Sorry about this. It should be `ts.distributed.init_process_group(group_size=2) `. I have fixed it in README. 

Please refer to the https://github.com/KaiyuYue/torchshard/blob/main/docs/api/dist.md#init_process_group.
