### ISSUE TITLE
Future Planinig on this project.

### ISSUE THREAD

**Issue by feifeibear** [KaiyuYue/torchshard#6]
Hello Kaiyu,
I love this awesome project. The API design is elegant and simple and the software is lightweight and user-friendly. My understanding is that this project has realized a series of PyTorch wrappers for tensor slicing. 
1. I am curious about the future planning of this project.
1. Is there some overlap in functionality between torchshard and N-D parallelism proposed in [ColossalAI](https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/nn/layer/parallel_2d/layers.py).
2. How is compatibility with ZeRO? According to [am+zero example](https://github.com/KaiyuYue/torchshard/blob/main/docs/tutorial/amp.md), the memory footprint has a little change after combination torchshard with ZeRO.

**Comment by kaiyuyue** [comment]
Hi Jiarui,

1. I have been planning to write a sampler. It aims to help users build the M-way data-parallel and N-way model parallel as easily as DistributedSampler with DDP. 
2. Those two projects have overlapped parts. It seems that the project was just released a month ago.
3. When I benchmark with ZeRO, I use the pre-built version of PyTorch. Now ZeRO has been an official class of the latest PyTorch. Maybe it will produce different results. 

Well, now I have a heavy workload of classes and can’t access the GPU training clusters. So the progress is slow. If you have any ideas about it, feel free to let me know.

**Comment by feifeibear** [comment]
> Hi Jiarui,
> 
> 1. I have been planning to write a sampler. It aims to help users build the M-way data-parallel and N-way model parallel as easily as DistributedSampler with DDP.
> 2. Those two projects have overlapped parts. It seems that the project was just released a month ago.
> 3. When I benchmark with ZeRO, I use the pre-built version of PyTorch. Now ZeRO has been an official class of the latest PyTorch. Maybe it will produce different results.
> 
> Well, now I have a heavy workload of classes and can’t access the GPU training clusters. So the progress is slow. If you have any ideas about it, feel free to let me know.

May I have your email address? You can send it to my Gmail.
